"""create log table now

Revision ID: 76bf48a510b6
Revises: 8b011f1883e2
Create Date: 2025-08-21 18:42:57.064729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76bf48a510b6'
down_revision: Union[str, Sequence[str], None] = '8b011f1883e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logger', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=200), nullable=True),
    sa.Column('func', sa.String(length=200), nullable=True),
    sa.Column('pathname', sa.String(length=500), nullable=True),
    sa.Column('lineno', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_logs_context_gin', 'app_logs', ['context'], unique=False, postgresql_using='gin')
    op.create_index('ix_app_logs_created_at', 'app_logs', ['created_at'], unique=False)
    op.create_index('ix_app_logs_level', 'app_logs', ['level'], unique=False)
    op.create_index('ix_app_logs_logger', 'app_logs', ['logger'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_logs_logger', table_name='app_logs')
    op.drop_index('ix_app_logs_level', table_name='app_logs')
    op.drop_index('ix_app_logs_created_at', table_name='app_logs')
    op.drop_index('ix_app_logs_context_gin', table_name='app_logs', postgresql_using='gin')
    op.drop_table('app_logs')
    # ### end Alembic commands ###
